
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
// Note: We intentionally avoid importing the generated Database types here,
// because src/integrations/supabase/types.ts is currently empty, which causes
// "never" types for tables/RPC and breaks TS. Once types are generated, we can
// re-introduce the generic to get strong typing.

const SUPABASE_URL = "https://adjwxqbdglbffzmqvmmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkand4cWJkZ2xiZmZ6bXF2bW10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NDc0MzUsImV4cCI6MjA3MDMyMzQzNX0.9rTwpk-3eZYyitiKjUyocf3kz6dazTT4CW2B7_NlGFo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
