// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adjwxqbdglbffzmqvmmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkand4cWJkZ2xiZmZ6bXF2bW10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NDc0MzUsImV4cCI6MjA3MDMyMzQzNX0.9rTwpk-3eZYyitiKjUyocf3kz6dazTT4CW2B7_NlGFo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});